db:
  host: 'localhost'
  type: 'postgres'
  port: 5432
  username: 'postgres'
  password: '12345'
  database: 'cms_criminal_manager'
  synchronize: false

queue:
  driver: 'redis'
  host: 'redis-15662.c270.us-east-1-3.ec2.redns.redis-cloud.com'
  port: 15662
  db: 'database-MFGUVS1J'
  password: 'haHvbHHOMAsySIwkAP0bhh6EAUYnlbbi'
  username: 'default'

jwt:
  secret: 'example@123'
